### ISSUE TITLE
JPEG Transcoding isn't lossless

### ISSUE THREAD

**Issue by jonnyawsom3** [awxkee/jxl-coder#20] opened 2024-09-24 17:19 UTC
Upstream for this issue https://github.com/T8RIN/ImageToolbox/issues/1363

JPEG transcoding should be bit-identical, but these additional EXIF tags are being added in ImageToolbox
```[File]          ExifByteOrder                   : Big-endian (Motorola, MM)
[IFD0]          ImageWidth                      : 1280
[IFD0]          ImageHeight                     : 960
[IFD0]          Orientation                     : Unknown (0)
[ExifIFD]       LightSource                     : Unknown
```

**Comment by awxkee** [comment] 2024-09-24 17:33
Did you tried to do it in sample app without any additional layers? Like this one.

```kotlin
val jxl = JxlCoder.Convenience.construct(buffer5)
val reconstructed = JxlCoder.Convenience.reconstructJPEG(jxl)
Log.d("TAG", "Source size ${buffer5.size}  reconstructed size ${reconstructed.size}")
```

If it doesn't match you have to ask explanation at libjxl team, this library does nothing on JPEG transcoding only sending to libjxl and passing back, without any changes.
To me it never adds any metadata.
You should check at first if it is matches using library. 
Your android OS may patch image on exporting from the app, anyway this is highly likely out of scope of this library.

**Comment by awxkee** [comment] 2024-09-24 17:37
And at may best understanding JPEG XL promising bit exact transcoding on quality not file size.
However it is highly unlikely that it will write any metadata also

**Comment by Quackdoc** [comment] 2024-09-24 18:36
libjxl decodes the file bitexact, the ending file, not just the frame, will have matching hashes if anything went right. I was able to replicate the issue using the toolbox app. I got matching file sizes but the hashes were different.

Using djxl on the "constructed" jxl does produce an image with matching hashes. I do not currently have time to make a demo program to try with but will upload a known bad image when I get a chance to. I verified with sha256sum.

**Comment by awxkee** [comment] 2024-09-24 18:59
If so then test code

```kotlin
fun sha256(input: ByteArray): String {
      val digest = MessageDigest.getInstance("SHA-256").digest(input)
      return digest.joinToString("") { "%02x".format(it) }
}

val jxl = JxlCoder.Convenience.construct(buffer5)
val reconstructed = JxlCoder.Convenience.reconstructJPEG(jxl)
Log.d("TAG", "Source size ${buffer5.size}  reconstructed size ${reconstructed.size}")
val originalHash = sha256(buffer5)
val reconstructedHash = sha256(reconstructed)
Log.d("TAG", "Original $originalHash")
Log.d("TAG", "Reconstructed $reconstructedHash")
Log.d("TAG", "Matches ${originalHash == reconstructedHash}")
```

Output 

```log
2024-09-24 19:54:26.037  4904-4929  TAG                     com.awxkee.jxlcoder                  D  Source size 395311  reconstructed size 395311
2024-09-24 19:54:26.042  4904-4929  TAG                     com.awxkee.jxlcoder                  D  Original 726b991eeecfb723f1bc0ac5c35b0d1176831586108c9f10aa2ba470b4f27efd
2024-09-24 19:54:26.042  4904-4929  TAG                     com.awxkee.jxlcoder                  D  Reconstructed 726b991eeecfb723f1bc0ac5c35b0d1176831586108c9f10aa2ba470b4f27efd
2024-09-24 19:54:26.043  4904-4929  TAG                     com.awxkee.jxlcoder                  D  Matches true
```

As I noted, lib itself does nothing, only calling libjxl apis. 
Perhaps the problem might be in specific file sizes if stream size do not handled correctly I think this is not really likely however might be, issue in libjxl vesion for specific images, or on exporting layer to your external storage from the app that is preferred option I consider.

**Comment by awxkee** [comment] 2024-09-24 18:59
Or importing code, to an internal app storage

**Comment by awxkee** [comment] 2024-09-24 19:00
Or both :)

**Comment by awxkee** [comment] 2024-09-24 19:45
I think dev of Toolbox suspects something https://github.com/T8RIN/ImageToolbox/commit/d66dadf7473e3b34d0c18fa22488220f2b622c38

**Comment by Quackdoc** [comment] 2024-09-24 20:55
yup, just tested their CI and the issue is fixed for me

**Comment by awxkee** [comment] 2024-09-24 20:58
So, I think the issues looks like have been resolved :) 

Closing for now.

**Closed by awxkee** 2024-09-24 20:58 UTC

**Comment by jonnyawsom3** [comment] 2024-09-25 00:48
Not sure why they didn't link it to my issue, but thanks for figuring it out you two
